./data result_32.txt >> data.txt
./data result_64.txt >> data.txt
./data result_128.txt >> data.txt
./data result_256.txt >> data.txt
./data result_512.txt >> data.txt
./data result_1K.txt >> data.txt
./data result_2K.txt >> data.txt
./data result_4K.txt >> data.txt
./data result_8K.txt >> data.txt
./data result_16K.txt >> data.txt
./data result_32K.txt >> data.txt
./data result_64K.txt >> data.txt
./data result_128K.txt >> data.txt
./data result_256K.txt >> data.txt
./data result_512K.txt >> data.txt
./data result_1M.txt >> data.txt
